### ISSUE TITLE
First run fails

### ISSUE THREAD

**Issue by jackbentley** [ocha/ansible-role-yarn#6]
Hello,

My first run of this role on a fresh CentOS 7 machine threw up this error. Not sure why?

No errors were thrown when running the playbook a second time immediately after. 

```
TASK [ocha.yarn : Check if YARN repo is already configured.] ******************************************************************************************************************************************************************************************************************************
ok: [<redacted>]

TASK [ocha.yarn : Install YARN YUM repo.] *************************************************************************************************************************************************************************************************************************************************
FAILED - RETRYING: Install YARN YUM repo. (3 retries left).
FAILED - RETRYING: Install YARN YUM repo. (2 retries left).
FAILED - RETRYING: Install YARN YUM repo. (1 retries left).
fatal: [<redacted>]: FAILED! => {"attempts": 3, "changed": false, "dest": "/etc/yum.repos.d/yarn.repo", "gid": 0, "group": "root", "mode": "0644", "msg": "file already exists", "owner": "root", "size": 130, "state": "file", "uid": 0, "url": "https://dl.yarnpkg.com/rpm/yarn.repo"}

```

Let me know if you need anymore info 🙂

**Comment by jackbentley** [comment]
It's being run as `root` 😕 Happy to do a little more debugging if you can't reproduce?

```yaml
---
- hosts: all
  become: true
```

**Comment by ocha** [comment]
Can you please post the version of the repo you are using, ansible, CentOS and attach a detailed log. you can use `-vvv` flag for verbose output

**Comment by jackbentley** [comment]
Hello, I went ahead and did some digging around. From what I can gather, the issue is to do with the `until` loop on the "Install YARN YUM repo." task. Not entirely sure of the point of the until loop?

The output from the `result` var from that task is:
```json
{
    "result": {
        "changed": true, 
        "checksum_dest": null, 
        "checksum_src": "da91775caef424acafb43eb8fe95005af945fdc4", 
        "dest": "/etc/yum.repos.d/yarn.repo", 
        "failed": false, 
        "gid": 0, 
        "group": "root", 
        "md5sum": "9c3303743a342602175010e3044f1b88", 
        "mode": "0644", 
        "msg": "OK (130 bytes)", 
        "owner": "root", 
        "size": 130, 
        "src": "/tmp/tmpjy0syO", 
        "state": "file", 
        "status_code": 200, 
        "uid": 0, 
        "url": "https://dl.yarnpkg.com/rpm/yarn.repo"
    }
}
```

I'm assuming that since the check is `until: '"failed" not in result'`, and it always has the `failed` key, it will keep looping.

If you really want the loop, then it'd probably work with `until: 'not result.failed`. However, I really don't see the point in the loop - so when I removed it, it was no longer erroring when the repo file didn't exist. It created it correctly and continued the playbook.

---

Version of plugin: `v.1.1.4`
Ansible Version: `2.5.0`
CentOS Version: `CentOS Linux release 7.4.1708 (Core)`
